### ISSUE TITLE
No View Selector after upgrade from 04.00.03

### ISSUE THREAD

**Issue by jhallen0916** [DNNCommunity/DNN.Announcements#36]
I recently upgraded dnn from version 08.00.04 to version 09.02.02. When I did the Announcements Modules I had been using on my sites failed. I then upgraded the Announcements Module from version 04.00.03 to 07.02.01. After upgrading I no longer have access to the dropdown list that allows me to choose between All, Expired, Current, and Future views from the page edit view.

**Comment by valadas** [comment]
It looks like it was like this since the beginning of the code history here, I am starting to believe the codebase from codeplex might not have been up to date and maybe Corp did a v4 release without updating codeplex source code... Sooo, kinda need to make this an enhancement as per the current state of things...

**Comment by valadas** [comment]
Since nobody indicated intentions to re-implement this I am closing this issues, but if anyone does intend to, just comment and I will reopen.
