### ISSUE TITLE
Please post a release for 9.2 compatibility

### ISSUE THREAD

**Issue by mattmol** [DNNCommunity/DNN.Announcements#9]
Not all users can compile or know how to..

**Comment by valadas** [comment]
@mattmol You can get the release zip files in the end of the comments on this pull request: https://github.com/DNNCommunity/DNN.Announcements/pull/6

@EPTamminga should also publish that release shortly ( I do not have write access ).

Also, if you see everything works fine in Dnn 9.2, please close this issue and if you run into any problems, please create an issue and I will correct promptly. This issue is pretty much the same as #8 , please close both after testing and create an new issue with error details if you encounter any problems in Dnn 9.2. Thanks.

**Comment by EPTamminga** [comment]
Release 07.02.00 posted with DNN 9.2 compatibility
